channels:
- conda-forge
dependencies:
- python=3.7
- pip:
  - azureml-core
  - azureml-defaults
  - joblib
  - azureml-sdk
  - pillow
  - tensorflow
  - numpy
  - itsdangerous==2.0.1
  - Flask==1.1.2
  - Jinja2<3.1.0
  - gunicorn
  - werkzeug==2.0.2

name: basic_env