channels:
- conda-forge
dependencies:
- python=3.7
- pip:
  - azureml-core
  - azureml-defaults
  - joblib
  - azureml-sdk
  - pillow
  - tensorflow
  - numpy
  - itsdangerous==2.0.1
  - Flask==2.0.3
  - Jinja2
  - gunicorn

name: basic_env