channels:
- conda-forge
dependencies:
- python=3.7
- pip:
  - azureml-core==1.27.0
  - azureml-defaults==1.27.0
  - joblib==1.1.0
  - azureml-sdk==1.27.0
  - pillow==9.0.1
  - tensorflow-gpu==1.15
  - numpy==1.21.5
  - itsdangerous==2.0.1

name: basic_env