channels:
- conda-forge
dependencies:
- python=3.7.1
- pip:
  - azureml-core
  - azureml-defaults
  - joblib==1.1.0
  - azureml-sdk
  - pillow
  - tensorflow==2.6.2
  - numpy
  - itsdangerous==2.0.1
  - Flask==2.0.3
  - Jinja2
  - gunicorn

name: basic_env