name: Yolov8 Remote Model Testing

trigger: none

pool:
  vmImage: ubuntu-20.04

variables:
- group: vars

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'ARMSC'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
        echo '--- Installing required libraries ---'
        cd model_zoo/ultralytics_yolov8
        git clone https://github.com/ultralytics/ultralytics.git
        mv ultralytics yolov8
        cd yolov8
        git checkout 59d43356644dd0df056e8d25cd5be92e0a1db88f
        cd ../../..

        pip install -r requirements.txt
        az config set extension.use_dynamic_install=yes_without_prompt
        az extension add -n ml -y

        echo '--- Setting variables ---'
        workspace_name=azoda-amlw
        resource_group=azoda-rg
        subscription_name="$(subscription_name)"
        subscription_id=$(az account list --query "[?name=='$subscription_name'].id | [0]" | jq . -r)
        tenant_id=$(az account list --query "[?name=='$subscription_name'].tenantId | [0]" | jq . -r)
        aml_storage_account_name_str=$(az ml datastore list --resource-group $resource_group --workspace-name $workspace_name --query "sort_by([].{account_name:account_name}[? contains(account_name, 'azoda')], &account_name)"[0].account_name)
        aml_storage_account_name=$(echo $aml_storage_account_name_str | tr -d \")
        aml_container_str=$(az ml datastore show --name workspaceblobstore --resource-group $resource_group --workspace-name $workspace_name --query container_name)
        aml_container=$(echo $aml_container_str | tr -d \")

        echo '--- Get dataset ---'
        az storage blob directory download -c $aml_container --account-name $aml_storage_account_name -s $(dataset)/ -d . --recursive

        echo '--- Get latest model timestamp ---'
        latest_checkpoint=$(az storage blob directory list --account-name $aml_storage_account_name -c $aml_container -d yolov8_models --query "sort_by([].{name:name}[? contains(name, 'best.pt')], &name)"[-1].name)
        latest_timestamp=${latest_checkpoint:15:13}
        echo $latest_timestamp
        
        echo '--- Get model ---'
        az storage blob directory download -c $aml_container --account-name $aml_storage_account_name -s yolov8_models/$latest_timestamp/train/weights/best.pt -d model_zoo/ultralytics_yolov8/loaded_weights/best.pt

        echo '--- Transform into yolo annotation format ---'
        python src/auto_setup/tf_to_yolo_annotations.py --dataset $(dataset) --model yolov8
        
        mv $(dataset).yaml model_zoo/ultralytics_yolov8/yolov8/
        mv $(dataset) model_zoo/ultralytics_yolov8/

        echo '--- Start remote testing job ---'
        python src/auto_setup/start_yolo_aml_run.py --dataset $(dataset) \
                                                    --tenant_id $tenant_id \
                                                    --service_principal_id $(service_principal_id) \
                                                    --service_principal_password $(service_principal_password) \
                                                    --subscription_id $subscription_id \
                                                    --resource_group $resource_group \
                                                    --workspace_name $workspace_name \
                                                    --mode test \
                                                    --model_source ultralytics_yolov8
