name: Setup Custom Vision Test

trigger: none

pool:
  vmImage: ubuntu-20.04

variables:
- group: vars

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'ARMSC'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |

      echo '--- Setting variables ---'
      subscription_id_str=$(az account list --query "[?isDefault].id | [0]")
      subscription_id=$(echo $subscription_id_str | tr -d \")
      tenant_id_str=$(az account list --query "[?isDefault].tenantId|[0]")
      tenant_id=$(echo $tenant_id_str | tr -d \")
      workspace_name=azoda-amlw
      resource_group=azoda-rg
      location=westeurope
      acr_name=$(echo azoda$subscription_id | tr -d -)
      cv_name=azodacv9

      echo '--- Installing required libraries ---'
      pip install azureml-sdk==1.39.0 numpy==1.22.3 opencv-python==4.5.5.62 pandas==1.4.1

      echo '--- Setting automatic yes to prompts ---'
      az config set extension.use_dynamic_install=yes_without_prompt

      echo '--- Setting devops configuration ---'
      az devops configure --defaults organization=https://dev.azure.com/$(organization_name) project=$(project_name)
      
      echo '--- Creating Custom Vision resource ---'
      az cognitiveservices account create --name $cv_name --resource-group $resource_group --kind CustomVision.Training --sku F0 --location westeurope
      
      echo '--- Getting Custom Vision key ---'
      key=$(az cognitiveservices account keys list --name $cv_name --resource-group $resource_group | jq -r ".key1")
      echo $key

      echo '--- Store Custom Vision secret in DevOps variable group ---'
      az pipelines variable-group variable create --group-id $(vargroup_id) --name testvar --secret false --value "test"
      az pipelines variable-group variable create --group-id $(vargroup_id) --name cv_key --secret false --value $key
