name: Yolov5 Model Training

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'ARMSC'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |

      echo '--- Installing required libraries ---'
      pip install -e src/packages/azure_utils
      az config set extension.use_dynamic_install=yes_without_prompt
      az extension add -n ml -y

      echo '--- Setting variables ---'
      workspace_name=tfod-dev-amlw
      resource_group=tfod-dev-rg-demo
      aml_storage_account_name_str=$(az ml datastore list --resource-group $resource_group --workspace-name $workspace_name --query "[0].{account_name:account_name}.account_name")
      aml_storage_account_name=$(echo $aml_storage_account_name_str | tr -d \")
      aml_container_str=$(az ml datastore show --name workspaceblobstore --resource-group $resource_group --workspace-name $workspace_name --query container_name)
      aml_container=$(echo $aml_container_str | tr -d \")

      echo '--- Get dataset ---'
      az storage blob directory download -c $aml_container --account-name $aml_storage_account_name -s remote_training_job.yml -d .

      echo '--- Start remote training job ---'
      az ml job create -f remote_training_job.yml --web --stream
