name: Model Training

trigger: none

name: Model training

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'ARMSC'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |

      echo '--- Setting variables ---'
      project=synthetic_dataset
      workspace_name=tfod-dev-amlw
      resource_group=tfod-dev-rg-demo
      acr_name=$(echo tfod$subscription_id | tr -d -)
      subscription_id_str=$(az account list --query "[?isDefault].id | [0]")
      subscription_id="${subscription_id_str:1:${#subscription_id_str}-2}"
      tenant_id_str=$(az account list --query "[?isDefault].tenantId|[0]")
      tenant_id="${tenant_id_str:1:${#tenant_id_str}-2}"

      echo '--- Installing required libraries ---'
      pip install -e src/packages/azure_utils
      pip install azureml-sdk==1.39.0

      echo '--- Writing dev_config.json ---'
      jq -n --arg tenant_id $tenant_id \
            --arg subscription_id $subscription_id \
            --arg workspace_name $workspace_name \
            --arg resource_group $resource_group \
            '{"AML_TENANT_ID": $tenant_id, "AML_WORKSPACE_NAME": $workspace_name, "AML_SUBSCRIPTION_ID": $subscription_id, "AML_RESOURCE_GROUP": $resource_group}' > dev_config.json
      cat dev_config.json
      jq . dev_config.json
      mv dev_config.json configuration/
      
      echo '--- Writing exp_config.json ---'
      python src/auto_setup/write_exp_config_json.py --experiment_name $project --acr $acr_name

      echo '--- Submit training job on AML ---'
      python src/training/submit_training.py
