name: Yolov5 Model Training

trigger: none

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'ARMSC'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |

      echo '--- Installing required libraries ---'
      pip install -e src/packages/azure_utils
      pip install matplotlib==3.5.1 numpy==1.22.3 pandas==1.4.1
      az config set extension.use_dynamic_install=yes_without_prompt
      az extension add -n ml -y

      echo '--- Setting variables ---'
      export DATASET=synthetic_dataset
      workspace_name=tfod-dev-amlw
      resource_group=tfod-dev-rg-demo
      aml_storage_account_name_str=$(az ml datastore list --resource-group $resource_group --workspace-name $workspace_name --query "[0].{account_name:account_name}.account_name")
      aml_storage_account_name=$(echo $aml_storage_account_name_str | tr -d \")
      aml_container_str=$(az ml datastore show --name workspaceblobstore --resource-group $resource_group --workspace-name $workspace_name --query container_name)
      aml_container=$(echo $aml_container_str | tr -d \")

      echo '--- Get dataset ---'
      az storage blob directory download -c $aml_container --account-name $aml_storage_account_name -s $(DATASET)/ -d "." --recursive

      echo '--- Transform into yolo annotation format ---'
      python src/auto_setup/tf_to_yolo_annotations.py --dataset $DATASET

      echo '--- Installing required libraries for yolov5 ---'
      cd models/yolov5
      pip install -r requirements.txt

      echo '--- Train model (1 epoch) ---'
      python train.py --data ../../synthetic_dataset.yaml --cfg yolov5n.yaml --weights '' --batch-size 16 --epochs 1
      
      echo '--- Store training run data to datastore ---'
      az storage blob directory upload -c $aml_container --account-name $aml_storage_account_name -s 'runs/train/exp/' -d '.' --recursive
