name: Import labels from Pixie

trigger: none

pool:
  vmImage: ubuntu-18.04

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true
    architecture: 'x64'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'ARMSC'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |

      echo '--- Installing required libraries ---'
      az config set extension.use_dynamic_install=yes_without_prompt
      pip install -e src/packages/azure_utils
      pip install azureml-sdk==1.39.0
      az extension add -n ml -y
      pip install --index-url https://pkgs.dev.azure.com/watchfor/WatchForTools/_packaging/w4Tools/pypi/simple/ watchfor-pixiev3==0.3.16
      sudo apt install ffmpeg -y
      pip uninstall ffmpeg-python -y
      pip install ffmpeg-python ffprobe packaging requests numpy opencv-python pandas

      echo '--- Setting variables ---'
      workspace_name=tfod-dev-amlw
      resource_group=tfod-dev-rg-demo
      subscription_id_str=$(az account list --query "[?isDefault].id | [0]")
      subscription_id=$(echo $subscription_id_str | tr -d \")
      tenant_id_str=$(az account list --query "[?isDefault].tenantId|[0]")
      tenant_id=$(echo $tenant_id_str | tr -d \")
      run_id_str=$(az ml job list --resource-group tfod-dev-rg --workspace-name tfod-dev-amlw --query "[0].name")
      run_id=$(echo $run_id_str | tr -d \")
      aml_storage_account_name_str=$(az ml datastore list --resource-group $resource_group --workspace-name $workspace_name --query "[0].{account_name:account_name}.account_name")
      aml_storage_account_name=$(echo $aml_storage_account_name_str | tr -d \")
      aml_container_str=$(az ml datastore show --name workspaceblobstore --resource-group $resource_group --workspace-name $workspace_name --query container_name)
      aml_container=$(echo $aml_container_str | tr -d \")

      echo '--- Import new labels from pixie project ---'
      cd src/auto_setup
      python import_from_pixie.py --api $(PIXIE_API) --key $(PIXIE_KEY) --dataset $(DATASET) --project_id $(PROJECT_ID) --export_labels
      az storage blob directory upload -c $aml_container --account-name $aml_storage_account_name -s 'labels_pixie.csv' -d '.'