name: Yolov5 Remote Model Training

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- group: vars

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'ARMSC'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |

      echo '--- Installing required libraries ---'
      pip install -e src/packages/azure_utils
      pip install matplotlib==3.5.1 numpy==1.22.3 pandas==1.4.1
      az config set extension.use_dynamic_install=yes_without_prompt
      az extension add -n ml -y

      echo '--- Setting variables ---'
      workspace_name=tfod-dev-amlw
      resource_group=tfod-dev-rg-demo
      subscription_id_str=$(az account list --query "[?isDefault].id | [0]")
      subscription_id=$(echo $subscription_id_str | tr -d \")
      tenant_id_str=$(az account list --query "[?isDefault].tenantId|[0]")
      tenant_id=$(echo $tenant_id_str | tr -d \")
      aml_storage_account_name_str=$(az ml datastore list --resource-group $resource_group --workspace-name $workspace_name --query "[0].{account_name:account_name}.account_name")
      aml_storage_account_name=$(echo $aml_storage_account_name_str | tr -d \")
      aml_container_str=$(az ml datastore show --name workspaceblobstore --resource-group $resource_group --workspace-name $workspace_name --query container_name)
      aml_container=$(echo $aml_container_str | tr -d \")

      echo '--- Get dataset ---'
      az storage blob directory download -c $aml_container --account-name $aml_storage_account_name -s $(dataset)/ -d . --recursive

      echo '--- Transform into yolo annotation format ---'
      python src/auto_setup/tf_to_yolo_annotations.py --dataset $(dataset)

      echo '--- Writing aml config.json ---'
      jq -n --arg subscription_id $subscription_id \
            --arg workspace_name $workspace_name \
            --arg resource_group $resource_group \
            '{"subscription_id": $subscription_id, "resource_group": $resource_group, "workspace_name": $workspace_name}' > config.json
      cat config.json
      
      cat $(dataset).yaml
      mv $(dataset).yaml models/yolo/
      mv $(dataset) models/yolo/

      echo 'ls'
      ls 
      echo 'ls models/yolo/'
      ls models/yolo

      echo '--- Start remote training job ---'
      python src/auto_setup/start_yolo_training.py --dataset $(dataset) \
                                                   --tenant_id $tenant_id \
                                                   --service_principal_id $(service_principal_id) \
                                                   --service_principal_password $(service_principal_password) \
                                                   --subscription_id $subscription_id \
                                                   --resource_group $resource_group \
                                                   --workspace_name $workspace_name \
