pool:
  vmImage: ubuntu-latest

steps:
- script: |     
    docker build . -f docker/tf_2/Dockerfile --no-cache
  displayName: 'Docker build'

- script: |
    docker images
  displayName: 'Show docker images'


- task: AzureCLI@2
  inputs:
    azureSubscription: 'ICARM'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |

      # Create resource group
      az group create --name tfod-dev-rg --location westeurope

      # Create a container registry
      az acr create --resource-group tfod-dev-rg --name tfoddevacr --sku Standard --admin-enabled true

      # Authenticate
      az acr login -n tfoddevacr

      # Get latest docker image id
      IMAGE_ID=$(docker images | awk '{print $3}' | awk 'NR==2')

      # Tag latest image
      docker tag $IMAGE_ID tfoddevacr.azurecr.io/tensorflowobjectdetection:latest

      # Push docker image to acr
      docker push tfoddevacr.azurecr.io/tensorflowobjectdetection:latest

      # Show docker containers
      docker container ls

      # Download tf2 model
      wget "http://download.tensorflow.org/models/object_detection/tf2/20200711/faster_rcnn_resnet50_v1_640x640_coco17_tpu-8.tar.gz"

      # Uncompress model
      tar -xf faster_rcnn_resnet50_v1_640x640_coco17_tpu-8.tar.gz

      # Set config to automatically agree to command without prompt
      az config set extension.use_dynamic_install=yes_without_prompt

      # Install required libraries
      pip install numpy opencv-python pandas

      # Create synthetic dataset
      python src/auto_setup/synthetic_dataset_creation.py

      # Create AML workspace
      az extension add -n ml -y
      az ml workspace create -n tfod-dev-amlw -g tfod-dev-rg --file azure-pipelines/templates/setup-aml.template.yml

      # Create gpu compute
      az ml compute create --max-instances 3 --name gpu-1 --size Standard_NC6 --workspace-name tfod-dev-amlw --resource-group tfod-dev-rg --no-wait --type AmlCompute

      # Get AML container name
      aml_storage_account_name_str=$(az ml datastore list --resource-group tfod-dev-rg --workspace-name tfod-dev-amlw --query "[0].{account_name:account_name}.account_name")
      aml_storage_account_name="${aml_storage_account_name_str:1:${#aml_stroage_account_name_str}-1}"

      # Create container in AML storage account
      az storage container create --name tfod-dev-container --account-name $aml_storage_account_name

      # Upload model and dataset to container
      az storage blob directory upload -c tfod-dev-container --account-name $aml_storage_account_name -s 'faster_rcnn_resnet50_v1_640x640_coco17_tpu-8/' -d 'models' --recursive
      az storage blob directory upload -c tfod-dev-container --account-name $aml_storage_account_name -s 'synthetic_dataset/' -d '.' --recursive
